export const START_AUTHENTICATION = 'START_AUTHENTICATION';
export const FACEBOOK_AUTHENTICATION_FAILED = 'FACEBOOK_AUTHENTICATION_FAILED';
export const FACEBOOK_AUTHENTICATION_SUCCESS = 'FACEBOOK_AUTHENTICATION_SUCCESS';
